global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "authecho-app"
    static_configs:
      - targets: ["host.docker.internal:6800"] # Use 'localhost:8000' if Prometheus and the metrics source are on the same machine without Docker.
